version: "3.9"
services:
    django_app:
        image: aabhinnavdocker/studybud:1.1
        container_name: django_cont
        ports:
          - 8000:8000
        depends_on:
          django_mysql:
            condition: service_healthy
    django_mysql:
        image: mysql:8.4
        container_name: django_mysql_container
        environment:
          MYSQL_DATABASE: 'django_db'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3